### ISSUE TITLE
Problems with loading the data/ matching labels to inputs

### ISSUE THREAD

**Issue by EvgeniaAR** [PatrykChrabaszcz/Imagenet32_Scripts#11]
Hi there,

I would like to use the downsampled version of ImageNet. I have downloaded the val+train files from https://image-net.org/download-images.php, the "npz format" versions. Then I ran "unzip Imagenet64_val_npz.zip" which resulted in a file called "val_data.npz".

I use python 3.6.8, and trying to load the file with the provided code results in the following error:
```
def load_data(input_file):

    d = unpickle(input_file)
    x = d['data']
    y = d['labels']

    x = np.dstack((x[:, :4096], x[:, 4096:8192], x[:, 8192:]))
    x = x.reshape((x.shape[0], 64, 64, 3))

    return x, y

def unpickle(file):
    with open(file, 'rb') as fo:
        dict = pickle.load(fo)
    return dict

x, y = load_data("./val64/Imagenet64_val_npz/val_data.npz")
Error: "UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified."
```

Using `x, y = np.load(input_file)` works, but the labels seem to be wrong, and the files are also unordered which is fine though. The shapes of x and y are `(50000, 64, 64, 3)` and `(50000,)`, respectively, so the file downloading, unzipping and loading seems to work (with np.load not with pickle).

These are the first five images in x with the labels y (and the human readable meanings taken from [here](https://gist.github.com/yrevar/942d3a0ac09ec9e5eb3a)):
![image](https://user-images.githubusercontent.com/34031285/155194079-49b6ed7b-19b0-483d-b61d-c39359dc7e22.png)

-> Does one have to manipulate the labels y to make them "correct" again?

Thank you for your help :)

**Comment by EvgeniaAR** [comment]
hm nevermind, I think the labels in this file (https://gist.github.com/yrevar/942d3a0ac09ec9e5eb3a) do not correspond to the files here (https://github.com/PatrykChrabaszcz/Imagenet32_Scripts/blob/master/map_clsloc.txt). 

Ok, so the labels are fine, but the unpickling does not work.

**Comment by kabbas570** [comment]
@EvgeniaAR Hi, you can use the following code for data/ matching labels to inputs.
https://github.com/kabbas570/ImageNet_DataGenerator
