### ISSUE TITLE
Aspect ratio

### ISSUE THREAD

**Issue by ciw-ws** [PatrykChrabaszcz/Imagenet32_Scripts#3]
Thanks for your great work.
I've found that aspect ratio is changed in this work. 
Is there a reason of why this is different to general ImageNet preprocessing? (center crop to keep the aspect ratio)

**Comment by PatrykChrabaszcz** [comment]
Hi @ciw-ws 

Yes, we change the aspect ratio of images.
As far as I know, on the original ImageNet dataset, people usually apply random cropping as a form of data augmentation when they train their networks. 

In general, we could extract crops from the center of the image. We could also apply any other preprocessing pipeline. 
I believe that for each potential preprocessing pipeline there are multiple arguments to support it.
I guess that the best way, but also with a high computational demand, would be to take the original ImageNet dataset and implement on-line resizing procedure as a part of the input preprocessing step with some random components.

In our dataset, we decided to resize full images for couple of reasons:
- It's super simple and intuitive.
- Humans do not have problems recognizing images that have slightly different aspect ratio.
- Sometimes, cropping might remove the labeled object from the image if it is placed at the edge. 
- Some images are high and narrow (look at the class: ski) and I noticed that after our resizing procedure I was sill able to tell what is on the picture
