### ISSUE TITLE
Batch size

### ISSUE THREAD

**Issue by tangbohu** [PatrykChrabaszcz/Imagenet32_Scripts#4]
Hi,
What batch size did you set on these experiments? Thanks

**Comment by tangbohu** [comment]
BTW, did you use SGD on these experiments reported in the paper.

**Comment by littlesnowperfume** [comment]
I also have this question about what is the batch_size number??

**Comment by littlesnowperfume** [comment]
HELLO:
@tangbohu  could we change e-mails to each others??
my email is paul8301526@gmail.com 
Maybe we could discuss this paper??
My wechat ID: paul8301526
HELLO:
I found he use batchsize=128 when use the GPU(Titan X)
![image](https://user-images.githubusercontent.com/25131251/54284401-d3cb1680-45da-11e9-8b60-5ea00a9ce901.png)

**Comment by PatrykChrabaszcz** [comment]
Hi, 
Indeed, it's 128:
https://github.com/PatrykChrabaszcz/Imagenet32_Scripts/blob/master/WRNs_imagenet.py#L318

It's SGD with momentum:
https://github.com/PatrykChrabaszcz/Imagenet32_Scripts/blob/master/WRNs_imagenet.py#L297
